apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cj-2
spec:
  schedule: 0 3 5 * *
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cj-2
              image: ubuntu
