apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cj-3-1234567891011121314151617181920212223242526272829303132343536373839
spec:
  schedule: 0 3 5 * *
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cj-3
              image: ubuntu
